### PR TITLE
Add pointer cursor for hovering menu

### PR DESCRIPTION
**Pull request by binbalenci**

### CODE REVIEW

**Review by homerjonathan — COMMENTED** [review]
Thanks for your updates. From first look seems fine. I am away from office but will check out first thing tomorrow.

**Review by homerjonathan — APPROVED** [review]
Thanks for the update.  This will improve the component.

**Comment by homerjonathan** [comment]
Updated.  Thanks for your contribution.

**Comment by binbalenci** [comment]
You're welcome!

**Pull request merged**
